/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookstoreproject;

public class App {
    public String makeAnnouncement() {
        return "Starting Project";
    }

    public static void main(String[] args) {
        System.out.println(new App().makeAnnouncement());
    }
}
